puddle/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index, contact

urlpatterns = [
    path('', index, name='index'),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('contact/', contact, name='contact'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/models.py
from django.db import models

# Create your models here.

puddle/item/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('created_at',)
        verbose_name_plural = 'Items'
    
    def __str__(self):
        return self.name

puddle/core/views.py
from django.shortcuts import render

from item.models import Category, Item
# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

puddle/item/views.py
from django.shortcuts import render, get_object_or_404

from .models import Item

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    
    return render(request, 'item/detail.html'), {
        'item': item
    }
    

puddle/core/templates/core/base.html
<!doctype <!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %} | Django Webstore for Training</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Puddle </a>
            <div class="space-x-6">
                <a href="#" class="text-lg font-semibold hover:text-red-500">New item</a>
                <a href="#" class="text-lg font-semibold hover:text-red-500">Browse</a>

                <a href="#" class="px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Login</a>
            </div>
        </nav>
       <div class="px-6 py-6">
        {% block content %}
        {% endblock %}       
       </div> 

       <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-bold text-gray-400">About</h3>
                <p class="text-lg text-gray-500"> LOREM IPSUM BLAHHHHHH </p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover text-teal-700">About</a></li>
                    <li><a href="{% url 'contact' %}" class="text-lg text-teal-500 hover text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover text-teal-700">Privacy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover text-teal-700">Terms of Service</a></li>

                </ul>

            </div>
        </footer>
    </body>
</html>

puddle/core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Contacts</h1>
{% endblock %}

puddle/core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>
        
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl" height="100px" width="auto">
                    </div>
    
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name}}</h2>
                        <p class="text-gray-500">Price: {{ item.price}}</p>
                    </div>
                </a>
            </div>
            {% endfor%}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            
            <a href="#">
                <div>
                    <img src="{{ item.image.url }}" class="rounded-t-xl">
                </div>

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ category.name}}</h2>
                    <p class="text-gray-500">{{ category.items.count}} items</p>
                </div>
            </a>
            
            {% endfor %}
        </div>
    </div>
{% endblock %}

puddle/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name}}{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ item.image.url}}" class="rounded-xl">
        </div>
    </div>
{% endblock %}